server:
  port: 80

eureka:
  client:
    service-url:
      defaultZone: http://eureka7001.com:7001/eureka/, http://eureka7002.com:7002/eureka/
    register-with-eureka: false

# 设置Feign客户端超时时间(OpenFeign默认支持ribbon)
ribbon:
  ReadTimeout: 5000
  connectTimeout: 5000


logging:
  level:
    # feign日志以什么级别监控哪个接口
    com.beluga.cloud.service.PaymentFeignService: debug