server:
  port: 9002

spring:
  application:
    name: nacos-payment-provider
  cloud:
    nacos:
      discovery:
        # 集群的话, 配置nginx的访问地址
        server-addr: 192.168.172.1:1111
      # server-addr: localhost:8848   # 配置 Nacos 地址
management:
  endpoints:
    web:
      exposure:
        include: '*'